[package]
name = "garbage_bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17", features = ["wav"] }
bevy_hanabi = "0.17"
rand = "0.9.2"

[profile.release]
opt-level = 's'
lto = true
codegen-units = 1

